 ;
 ; Basic Test for Query parser
 ;
QP ;
 N QUERY,PARAMS
 ; Two birds test: first op name is valid but rest isn't
 S QUERY="DESCRIBEX NONSENSE AND MORE"
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR="" W "0. "_QUERY_" - FAIL: NO EXPECTED ERROR",! Q
 W "0. "_QUERY_" - SUCCESS - "_ERROR,!
 S QUERY="SELECT 2"
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "1. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("OP"))'="SELECT" W "1. BAD OP",! Q
 I $G(PARAMS("TYPE"))'=2 W "1. BAD TYPE",! Q
 W "1. "_QUERY_" - SUCCESS",!
 S QUERY="DESCRIBE 2-1"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "2. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("OP"))'="DESCRIBE" W "2. BAD OP",! Q
 I $G(PARAMS("TYPE"))'=2 W "2. BAD TYPE",! Q
 I $G(PARAMS("ID"))'=1 W "2. BAD ID",! Q
 W "2. "_QUERY_" - SUCCESS",!
 S QUERY="SELECT 2 LIMIT 100 OFFSET 10"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "3. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("OP"))'="SELECT" W "3. BAD OP",! Q
 I $G(PARAMS("TYPE"))'=2 W "3. BAD TYPE",! Q
 I $G(PARAMS("LIMIT"))'=100 W "3. BAD LIMIT",! Q
 I $G(PARAMS("OFFSET"))'=10 W "3. BAD OFFSET",! Q
 W "3. "_QUERY_" - SUCCESS",!
 ; Non numeric LIMIT is an ERROR
 S QUERY="SELECT 2 LIMIT 100X"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR="" W "4. "_QUERY_" - FAIL: NO EXPECTED ERROR",! Q
 W "4. "_QUERY_" - SUCCESS - "_ERROR,!
 S QUERY="DESCRIBE 2-1 CSTOP 100"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "5. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("CNODESTOP"))'=100 W "5. CSTOP not parsed to I Name",! Q
 W "5. "_QUERY_" - SUCCESS",!
 ; No type or ID
 S QUERY="SELECT LIMIT 100"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR="" W "6. "_QUERY_" - FAIL: NO EXPECTED ERROR",! Q
 W "6. "_QUERY_" - SUCCESS - "_ERROR,!
 S QUERY="SELECT 2 LIMIT"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR="" W "7. "_QUERY_" - FAIL: NO EXPECTED ERROR",! Q
 W "7. "_QUERY_" - SUCCESS - "_ERROR,!
 S QUERY="SELECT TYPES"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "8. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("OP"))'="SELECT TYPES" W "8. OP not correct: "_$G(PARAMS("OP")),! Q
 W "8. "_QUERY_" - SUCCESS",!
 S QUERY="SELECT TYPES TOPONLY POPONLY"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "9. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("TOPONLY"))'=1 W "9. TOPONLY not set",! Q
 I $G(PARAMS("POPONLY"))'=1 W "9. POPONLY not set",! Q
 W "9. "_QUERY_" - SUCCESS",!
 S QUERY="DESCRIBE 63_04 IN 63-4 LIMIT 10"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "9. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("IN"))'="63-4" W "10. IN Not Taken",! Q
 I $G(PARAMS("TYPE"))'="63_04" W "10. TYPE Not Taken",! Q
 I $G(PARAMS("LIMIT"))'=10 W "10. LIMIT Not Taken",! Q
 W "10. "_QUERY_" - SUCCESS",!
 S QUERY="DESCRIBE TYPE 2"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "11. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("FOP"))'="DESCRIBE TYPE" W "11. OP Incorrect",! Q
 I $G(PARAMS("TYPE"))'=2 W "11. TYPE Wrong",! Q
 W "11. "_QUERY_" - SUCCESS",!
 ; Testing keyword inclusion in filter is taken care of
 S QUERY="SELECT 2 LIMIT 100 FILTER (.02=OFFSET) OFFSET 10"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "12. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("OP"))'="SELECT" W "12. BAD OP",! Q
 I $G(PARAMS("TYPE"))'=2 W "12. BAD TYPE",! Q
 I $G(PARAMS("LIMIT"))'=100 W "12. BAD LIMIT",! Q
 I $G(PARAMS("OFFSET"))'=10 W "12. BAD OFFSET",! Q
 I $G(PARAMS("FILTER"))'=".02=OFFSET" W "12. BAD FILTER",! Q
 W "12. "_QUERY_" - SUCCESS",!
 S QUERY="SELECT 2 LIMIT 100 FILTER(.02=2-9) OFFSET 10"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "13. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("FILTER"))'=".02=2-9" W "13. BAD FILTER",! Q
 W "13. "_QUERY_" - SUCCESS",!
 S QUERY="SELECT 2 FILTER(.02=2-9)"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "14. UNEXPECTED ERROR - "_ERROR,! Q
 I $G(PARAMS("FILTER"))'=".02=2-9" W "14. BAD FILTER",! Q
 W "14. "_QUERY_" - SUCCESS",!
 S QUERY="SELECT 2 FILTER(.02=2-9"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR="" W "15. "_QUERY_" - FAIL: NO EXPECTED ERROR",! Q
 W "15. "_QUERY_" - SUCCESS - "_ERROR,!
 S QUERY="SELECT 2 FILTER .02=2-9)"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR="" W "16. "_QUERY_" - FAIL: NO EXPECTED ERROR",! Q
 W "16. "_QUERY_" - SUCCESS - "_ERROR,!
 W "17. DUMMY - to be filled in",!
 S QUERY="DESCRIBE BADTYPES"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "18. UNEXPECTED ERROR - "_ERROR,! Q
 W "18. "_QUERY_" - SUCCESS",!
 S QUERY="COUNT _114 IN _11-.1102"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "19. UNEXPECTED ERROR - "_ERROR,! Q
 I '$D(PARAMS("IN")) W "19. UNEXPECTED ERROR - NO 'IN' PARSED",! Q
 W "19. "_QUERY_" - SUCCESS",!
 S QUERY="SELECT 120_5 FILTER(.02=2-9&!bound(2)&.03=120_51-8)"
 K PARAMS
 S ERROR=$$PRSQUERY^FMQLQP(QUERY,.PARAMS)
 I ERROR'="" W "20. UNEXPECTED ERROR - "_ERROR,! Q
 ; Tries out Embedded )'s
 I PARAMS("FILTER")'=".02=2-9&!bound(2)&.03=120_51-8" W "20. UNEXPECTED ERROR - FILTER NOT PARSED PROPERLY",! Q
 W "20. "_QUERY_" - SUCCESS",!
 Q

